<?php

namespace App\Service;

use Symfony\Component\DependencyInjection\Container;

class LanguageService
{

    public function getLanguages()
    {
        $langs = array(
            'eng' => 'English',
            'rus' => 'Русский',
            'afr' => 'Afrikaans',
            'alb' => 'Shqiptar',
            'apd' => 'Sunda',
            'ara' => 'العربية',
            'arm' => 'հայերեն',
            'aze' => 'Azərbaycan',
            'baq' => 'Euskal',
            'bel' => 'Беларуская',
            'ben' => 'বাঙালি',
            'bos' => 'Bosanski',
            'bul' => 'Български',
            'bur' => 'မြန်မာ',
            'cat' => 'Català',
            'ceb' => 'Sebuanskij',
            'cym' => 'Cymraeg',
            'cze' => 'Čeština',
            'dut' => 'Dansk',
            'epo' => 'Esperanta',
            'est' => 'Eesti',
            'fin' => 'Suomi',
            'fre' => 'Français',
            'geo' => 'ქართული',
            'ger' => 'Deutsch',
            'gle' => 'Irish',
            'glg' => 'Galego',
            'gre' => 'ελληνικά',
            'guj' => 'ગુજરાતી',
            'hat' => 'Kreyòl (Ayiti)',
            'hau' => 'House',
            'heb' => 'עברית',
            'hin' => 'हिंदी',
            'hmn' => 'Hmong',
            'hrv' => 'Hrvatski',
            'hun' => 'Magyar',
            'ibo' => 'Igbo',
            'ice' => 'Icelandic',
            'ind' => 'Bahasa Indonesia',
            'ita' => 'Italiano',
            'jav' => 'Jawa',
            'jpn' => '日本人',
            'kan' => 'ಕನ್ನಡ',
            'kaz' => 'Қазақ',
            'khm' => 'ខ្មែរ',
            'kor' => '한국의',
            'lao' => 'ລາວ',
            'lat' => 'Latine',
            'lav' => 'Latvijas',
            'lit' => 'Lietuvos',
            'mac' => 'Macedonike',
            'mal' => 'മലയാളം',
            'mao' => 'Maori',
            'mar' => 'मराठी',
            'may' => 'Melayu',
            'mlg' => 'Malagasy',
            'mlt' => 'Malti',
            'mon' => 'Монгол улсын',
            'nep' => 'नेपाली',
            'nld' => 'Nederlands',
            'nor' => 'Norsk',
            'nya' => 'Chev',
            'pan' => 'ਪੰਜਾਬੀ ਦੇ',
            'per' => 'فارسی',
            'pol' => 'Polski',
            'por' => 'Português',
            'rum' => 'Român',
            'sin' => 'සිංහල',
            'slk' => 'Slovenčina',
            'slv' => 'Slovenščina',
            'som' => 'Somalia',
            'sot' => '-sinhali',
            'spa' => 'Español',
            'srp' => 'Сербскии',
            'swa' => 'Kiswahili',
            'swe' => 'Svenska',
            'tai' => 'ไทย',
            'tam' => 'தமிழ்',
            'tel' => 'తెలుగు',
            'tgk' => 'Тоҷикистон',
            'tgl' => 'Tagalog',
            'tur' => 'Türk',
            'ukr' => 'Українська',
            'urd' => 'اردو',
            'uzb' => 'O\'zbekiston',
            'vie' => 'Tiếng Việt',
            'yid' => 'ייִדיש',
            'yor' => 'Yoruba',
            'lzh' => '中國（繁體)',
            'zho' => '中国（简体)',
            'zul' => 'Zulu',
        );
        return $langs;
    }

}
